version = 1

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "17"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["angular"]
  environment = [
    "nodejs",
    "jasmine",
    "jest",
    "browser",
    "vitest"
  ]