version: '3.8'
services:
  sp-api:
    container_name: sp-api
    image: suiviephysique/sp-api:latest
    env_file:
      - app.env
    ports:
      - "3008:3008"
    networks:
        - sp-network
  sp-ui:
    container_name: sp-ui
    image: suiviephysique/sp-ui:latest
    depends_on:
      - sp-api
    ports:
      - "80:80"
    networks:
        - sp-network

networks:
  sp-network:
      driver: bridge
