version: '3.8'
services:
  backend:
    image: backend
    build: ./backend
    ports:
      - "3008:3008"
    networks:
        - sp-network
  frontend:
    image: frontend
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
        - sp-network

#  mail-dev:
#    container_name: maildev-sp
#    image: maildev/maildev
#    ports:
#      - "1080:1080"
#      - "1025:1025"
#    networks:
#        - sp-network
#    restart: unless-stopped

networks:
  sp-network:
      driver: bridge
